### ISSUE TITLE
Adapt button colors for outdoor use

### ISSUE THREAD

**Issue by dlmw** [CPNV-ES/Joutes-2020#32]
Prise en charge le ..., par ...

# Analyse du problème

## Fonctionnement actuel

La couleur de fond du bouton est vert-clair et celle du texte blanc.

## Description du problème

Lors d'une utilisation en extérieur, les boutons (fond vert-clair/texte blanc) sont difficilement visibles.

## Description de la solution

(Terminé, le ...)

# Plan d'intervention

(Terminé, le ...)

# Exécution

## Tests

(Terminés, le ...)

# Documentation

(Mise à jour, le ...)

**Comment by BPTdev** [comment]
We conclude that the actuals colors are a good mix of contrast.
Apart from making the background black (not good for computer screen under summer sun) the contrast will not be improved.
